cm.LibraryBrowserCustomizer.applyOrder({'BWB_library',1, ...
                                        'CA_library',1, ...
                                        'FDI', 1,...
                                        'SMC', 1});
                                        